o Fix the second issue of Error that was coming after PayPAL returns successfully from donation processing.
Error: Server Error
The server encountered an error and could not complete your request.
dd																																																																																																																																																																																															

If the problem persists, please report your problem and mention this error message and the query that caused it.

http://www.iskconsv.org/payment-complete/?tx=7GF26385UU1065220&st=Completed&amt=1.00&cc=USD&cm=&item_number=&sig=FVR5gbFQ%2fCrCXdvxE9UUoL0lb2BKSwKiiHkE5l7tv%2bUeV%2fiv4Z3VGpBSwDF%2bP2%2fEBYiyRuQj5qodIrCwgNAPAqX01zeUefTVNoPSDeBnr0%2f8UXTYvhvbFGCdKK%2fb70G7uRJHikP0vSzCIqb%2fUK4%2fgNNDh3XMz2D31fl3mw8D%2bTs%3d